### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anthonycorbacho** [leesper/couchdb-golang#11]
Hello 👋 

I wanted to know if you are going to add a new release? the latest version `v1.2.1` was released Jan 2017.

**Comment by leesper** [comment]
@anthonycorbacho oh, well, thank you for your information, I'll take a look when I am free, a little busy these days  : )

**Comment by anthonycorbacho** [comment]
Awesome, thanks for replying, if you need any help please let me know :)

**Comment by leesper** [comment]
@anthonycorbacho haha, thank you for your kindness! This is an open-source project for everybody, you are welcome to contribute your code ! The only requirement is, please add your unit tests, have fun : )
